Repository BlackArch/blackarch, pull requests merged in 2021-02, with the labels that each got.

#3006 chipsec: Updated fixes in light of previous commit
  packages/chipsec/Makefile.patch
  packages/chipsec/PKGBUILD
Labels: not-ready-to-merge

#3029 New tool: enumerate-iam
  lists/to-release
  packages/enumerate-iam/PKGBUILD
Labels: lang::python, type-newtool

#3034 darkarmour dep osslsigncode fix #3032
  lists/to-release
  packages/osslsigncode/PKGBUILD
Labels: lang::c

#3033 darkarmour fix #3032
  lists/to-release
  packages/darkarmour/PKGBUILD
Labels: lang::python
